name: build-deps

on:
  push:
    branches:
      - "main"
    paths:
      - "vendor/lexbor-src"
      - "vendor/netsurf/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lightpanda-io/browsercore-deps
  ZIG_DOCKER_VERSION: 0.12.0-dev.3518-d2be725e4

jobs:
  build-deps:
    strategy:
      matrix:
        include:
          - os: linux
            build_arch: amd64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_CI_PAT }}
          submodules: true

      - name: Docker connect
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker build
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile.deps
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.ZIG_DOCKER_VERSION}}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ZIG_DOCKER_VERSION=${{ env.ZIG_DOCKER_VERSION }}
          platforms: ${{matrix.os}}/${{matrix.build_arch}}
